### ISSUE TITLE
TODO TOTHINK

### ISSUE THREAD

**Issue by snantipat** [swopdome/Hunter-s-Adventure-Game#1]
1.ในคลาส State interface interface waveInfo
   - [x] battle
   - [x] using item
   - [x] wave at State
   - [x] result

2.waveInfoยังไม่ได้ทำ
3.monster ใน wave ยังไม่ได้ใส่
4.การโจมตีของเราที่ใช้ชนิดของอาวุธยังไม่ได้คิด
5.ระบบ item
6.การซื้อขายกับnpc

**Comment by swopdome** [comment]
_`done!`_

**Comment by snantipat** [comment]
_Done!_
