### ISSUE TITLE
papaya pock pock (state wave battle)

### ISSUE THREAD

**Issue by ukkpaapay** [swopdome/Hunter-s-Adventure-Game#2]
ที่มี
-มี state wave battle 
-พอเลือกstateก็จะเข้าswitch(op)จะได้รู้ว่าด่านไหนมีกี่wave
-พวกอาวุธแค่เขียนหาแนวคิดเฉยๆ
-yourbattleคือtrunของเรา
-ค่าต่างๆแค่ทดลอง
monbattleคือtrunของมอน
ที่ขาด
-ไม่มีระบบที่เลือดหมดแล้วหลุดหลูบที
`    public static void main(String[] args) {
    state();
        }
        public static void state(){
            int op ;
            do{
            Scanner state = new Scanner(System.in);
            System.out.println("state: ");
             op = state.nextInt();
            }while(op>=10);
            switch(op){
                case 1:for(int y=1 ; y<=2 ; y++){wave();};break;
                case 2:for(int y=1 ; y<=2 ; y++){wave();};break;
                default:for(int y=0 ; y<=2 ; y++){wave();};break;
            }
        } `

     `  public static void wave(){
        weapon();    
        }
        public static void weapon() {
    Scanner weapon = new Scanner(System.in);
    System.out.println("(1)Greatswords (2)Sword (3)Daggers");
    int w = weapon.nextInt();
    switch(w){
        case 1 :do{
                  YourBattle();
                  MonsBattle();
                  }while(/*เลือดใครหมด*/);break;
        case 2 :do{
                  YourBattle();
                  YourBattle();
                  MonsBattle();
                  }while(/*เลือดใครหมด*/);break;
        case 3 :do{
                  YourBattle();
                  YourBattle();
                  YourBattle();
                  MonsBattle();
                  }while(/*เลือดใครหมด*/);break;

        }
        public static void YourBattle(){   
     int m1=100,m2=150,m3=200,atk=50,hp=100;
     System.out.println("==================Your trun===========================");
     System.out.println("trun name");
     System.out.println("Your Hp: "/*เลือดเรา*/);
     System.out.println("  (1)	        		(2)			(3)");
     System.out.println(" hp"+/*เลือดมอน*/+"	        	       hp"+/*เลือดมอน*/+"  	               hp"/*เลือดมอน*/);
     System.out.println(" power 5		       power 4		       power 10");
     System.out.println(" name_mon		       name_mon		       name_mon");
     Scanner sr = new Scanner(System.in);
     System.out.print("choose: ");
     int s = sr.nextInt();
     int a = 0;
     switch(s){
            case 1 :     a = m1-atk ;break;
            case 2 :     a = m2-atk ;break;
            case 3 :     a = m3-atk ;break;
     }

        }
        public static void MonsBattle(){
            int am1=5,am2=4,am3=10,dm=0,hp=0;
            System.out.println("==================Monster trun=======================");
    System.out.println("trun Monster");
    System.out.println("name_mon1 attacked "+/*พลังโจมตีมอน*/+" dmg\n" +
                       "name_mon2 attacked "+/*พลังโจมตีมอน*/+" damg\n" +
                       "name_mon3 attacked "+/*พลังโจมตีมอน*/+" dmg");
    dm=(/*พลังโจมตีมอน*/+/*พลังโจมตีมอน*/+/*พลังโจมตีมอน*/)-/*เลือดเรา*/;
        }

    } `

**Comment by snantipat** [comment]
ทำดีๆเดะคิด Class State กันใหม่

**Comment by snantipat** [comment]
_Done!_
